-- Run once in Supabase SQL Editor if rebuilding the database.
-- Replace the owner UUID in your RLS policies with your Supabase Auth user UID.

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null default 'Activity',
  description text default '',
  tools text default '',
  learnings text default '',
  evidence_url text default '',
  completed_on date not null,
  created_at timestamptz not null default now()
);

create table if not exists public.activity_comments (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.activities(id) on delete cascade,
  visitor_name text not null,
  comment text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.site_feedback (
  id bigint generated by default as identity primary key,
  visitor_name text not null,
  feedback text not null,
  created_at timestamptz not null default now()
);

-- The current project's RLS policies are already configured in Supabase.
-- Keep RLS enabled and never expose a service-role key in website source.
